# Modification of column names

Read the file **product_prices.csv** into a DataFrame. Modify the names of columns so that they match those in the  **product_prices_renamed.csv** file. Complete two variants of the exercise:

1. Using the `rename` method,
1. Overwriting all column names using `columns`.

To unify the naming and reduce the risk of a **typo**, you can use the dictionary below:
```
{'Name': 'province',
 'Types of goods': 'product_types',
 'Measurement unit': 'currency',
 'id': 'id',
 'Types of products': 'product_line',
 'Value': 'value',
 'Date': 'date'}```

> The `columns` method overwrites the columns directly on the object (does not return a new DataFrame), so if you do step 2 first, the hint will be useless (the columns get overwritten).

In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('../../01_Data/product_prices.csv', sep=';', decimal='.')

In [6]:
data

,Name,Goods types,Measurement unit,Group ID,Product types,Value,Date
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3
...,...,...,...,...,...,...,...
149935,KUYAVIA-POMERANIA,NaN,PLN,2,pork meat (raw bacon) - per 1kg,12.15,2016-11
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3,NaN,0.00,2012-5
149937,LESSER POLAND,NaN,PLN,4,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6
149938,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11
149939,MASOVIA,NaN,PLN,4,Masurian barley groats - per 1kg,0.16,2005-10

In [44]:
data_rename = data.rename(columns = {'Name': 'province',
    'Types of goods': 'product_types',
    'Measurement unit': 'currency',
    'id': 'id',
    'Types of products': 'product_line',
    'Value': 'value',
    'Date': 'date'})

In [38]:
data_rename = data.rename(columns = str.upper)

In [40]:
data_rename

,PROVINCE,PRODUCT_TYPES,CURRENCY,ID,PRODUCT_LINE,VALUE,DATE
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3
...,...,...,...,...,...,...,...
149935,KUYAVIA-POMERANIA,NaN,PLN,2,pork meat (raw bacon) - per 1kg,12.15,2016-11
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3,NaN,0.00,2012-5
149937,LESSER POLAND,NaN,PLN,4,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6
149938,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11
149939,MASOVIA,NaN,PLN,4,Masurian barley groats - per 1kg,0.16,2005-10

In [18]:
data.columns = ['province', 'product_types', 'currency', 'id', 'product_line', 'value', 'date']

In [20]:
data

,province,product_types,currency,id,product_line,value,date
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3
...,...,...,...,...,...,...,...
149935,KUYAVIA-POMERANIA,NaN,PLN,2,pork meat (raw bacon) - per 1kg,12.15,2016-11
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3,NaN,0.00,2012-5
149937,LESSER POLAND,NaN,PLN,4,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6
149938,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11
149939,MASOVIA,NaN,PLN,4,Masurian barley groats - per 1kg,0.16,2005-10