# Dataset normalization

In the sheets of the **dims.xlsx** file there are dictionaries for the data from the **product_prices_cleaned.csv** file. Use `merge` to normalize the data following the steps:

1. Read the contents of the **dims.xlsx** file sheets to separate `DataFrames`.
For readability base names of frames on the names of sheets.

1. Read the data from **product_prices_cleaned.csv** file to the `df` variable.

1. Based on the **d_province** workbook, use the `id` column to add the `province_id` column to the `df` frame.

1. Based on the  **d_product** workbook, add the `product_id` column to the `df` frame.

1. From the table, extract only the columns that refer to other tables, e.g.. **product_id** and the columns **value**, **date**. Do you think this is more readable? What are potential benefits of this approach?

> We will tell you how to read many workbooks at once when we discuss `openpyxl`.

You can find more about database normalization at the [link](https://www.sqlshack.com/what-is-database-normalization-in-sql-server/).

In [1]:
import pandas as pd

In [4]:
data_dims_product = pd.read_excel(
    r'../../01_Data\dims.xlsx',
    sheet_name = 'd_product'
)

In [5]:
data_dims_province = pd.read_excel(
    r'../../01_Data\dims.xlsx',
    sheet_name = 'd_province'
)

In [6]:
data_dims_product_group = pd.read_excel(
    r'../../01_Data\dims.xlsx',
    sheet_name = 'd_product_group'
)

In [7]:
data_cleaned = pd.read_csv(
  '../../01_Data/product_prices_cleaned.csv',
  sep=';',
  encoding='UTF-8',
  decimal='.'
)

In [8]:
join_province = pd.merge(
    left = data_cleaned,
    right = data_dims_province,
    how='left',
    left_on=['province'],
    right_on=['province']
)

In [9]:
join_province

,province,product_types,currency,product_group_id,product_line,value,date,product,province_id
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg,8.0
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2,bread - per 1kg,14.0
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg,2.0
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg,1.0
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg,11.0
...,...,...,...,...,...,...,...,...,...
128515,SILESIA,NaN,PLN,2,smoked bacon with ribs - per 1kg,15.95,2015-9,smoked bacon with ribs - per 1kg,15.0
128516,SILESIA,NaN,PLN,2,barley groats sausage - per 1kg,4.50,2004-8,barley groats sausage - per 1kg,15.0
128517,KUYAVIA-POMERANIA,NaN,PLN,2,pork meat (raw bacon) - per 1kg,12.15,2016-11,pork meat (raw bacon) - per 1kg,2.0
128518,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3,NaN,0.00,2012-5,"beet sugar white, bagged - per 1kg",14.0
128519,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.0

In [10]:
data_dims_product

,product_id,product,product_group_id
0,20,pork ham cooked - per 1kg,2
1,26,bread - per 1kg,4
2,10,barley groats sausage - per 1kg,2
3,12,dressed chickens - per 1kg,2
4,19,Italian head cheese - per 1kg,2
5,5,pork belly cooked - per 1kg,2
6,14,pork with bone (center-cut pork chop) - per 1kg,2
7,27,plain mixed bread (wheat-rye) - per 1kg,4
8,30,"Poznan wheat flour, bagged - per 1kg",4
9,8,fresh non-dressed carp - per 1kg,2
10,1,30% tomato concentrate - per 1kg,1
11,6,smoked bacon with ribs - per 1kg,2
12,7,haddock fillets frozen - per 1kg,2
13,21,"salted herring, non-dressed - per 1kg",2
14,28,buckwheat groats roasted whole - per 1kg,4
15,17,beef with bone (rump steak) - per 1kg,2
16,2,frozen carrot and pea mix - per 1kg,1
17,22,"beet sugar white, bagged - per 1kg",3
18,16,boneless beef (sirloin) - per 1kg,2
19,29,Masurian barley groats - per 1kg,4
20,25,white table salt bagged - per 1kg,3
21,23,natural chocolate plain - per 1kg,3
22,13,pork meat (raw bacon) - per 1kg,2
23,15,pork meat with bone (shoulder) - per 1kg,2
24,9,Hunter's sausage dried - per 1kg,2
25,3,whole pickled cucumbers 0.9l - per 1pc.,1
26,24,fresh chicken egs - per 1 pc.,3
27,4,"apple juice, boxed - per 1l",1
28,18,fresh non-dressed trout - per 1kg,2
29,11,Backpacker's canned pork meat - per 300 g,2

In [11]:
data_dims_product.rename(columns={'product': 'product_line'}, inplace=True)

In [12]:
data_dims_product

,product_id,product_line,product_group_id
0,20,pork ham cooked - per 1kg,2
1,26,bread - per 1kg,4
2,10,barley groats sausage - per 1kg,2
3,12,dressed chickens - per 1kg,2
4,19,Italian head cheese - per 1kg,2
5,5,pork belly cooked - per 1kg,2
6,14,pork with bone (center-cut pork chop) - per 1kg,2
7,27,plain mixed bread (wheat-rye) - per 1kg,4
8,30,"Poznan wheat flour, bagged - per 1kg",4
9,8,fresh non-dressed carp - per 1kg,2
10,1,30% tomato concentrate - per 1kg,1
11,6,smoked bacon with ribs - per 1kg,2
12,7,haddock fillets frozen - per 1kg,2
13,21,"salted herring, non-dressed - per 1kg",2
14,28,buckwheat groats roasted whole - per 1kg,4
15,17,beef with bone (rump steak) - per 1kg,2
16,2,frozen carrot and pea mix - per 1kg,1
17,22,"beet sugar white, bagged - per 1kg",3
18,16,boneless beef (sirloin) - per 1kg,2
19,29,Masurian barley groats - per 1kg,4
20,25,white table salt bagged - per 1kg,3
21,23,natural chocolate plain - per 1kg,3
22,13,pork meat (raw bacon) - per 1kg,2
23,15,pork meat with bone (shoulder) - per 1kg,2
24,9,Hunter's sausage dried - per 1kg,2
25,3,whole pickled cucumbers 0.9l - per 1pc.,1
26,24,fresh chicken egs - per 1 pc.,3
27,4,"apple juice, boxed - per 1l",1
28,18,fresh non-dressed trout - per 1kg,2
29,11,Backpacker's canned pork meat - per 300 g,2

In [13]:
join_province_product = pd.merge(
    left = join_province,
    right = data_dims_product,
    how='left',
    left_on=['product_group_id'],
    right_on=['product_group_id']
)

In [14]:
join_province_product

,province,product_types,currency,product_group_id,product_line_x,value,date,product,province_id,product_id,product_line_y
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg,8.0,20,pork ham cooked - per 1kg
1,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg,8.0,10,barley groats sausage - per 1kg
2,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg,8.0,12,dressed chickens - per 1kg
3,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg,8.0,19,Italian head cheese - per 1kg
4,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg,8.0,5,pork belly cooked - per 1kg
...,...,...,...,...,...,...,...,...,...,...,...
1482259,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.0,13,pork meat (raw bacon) - per 1kg
1482260,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.0,15,pork meat with bone (shoulder) - per 1kg
1482261,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.0,9,Hunter's sausage dried - per 1kg
1482262,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.0,18,fresh non-dressed trout - per 1kg
1482263,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.0,11,Backpacker's canned pork meat - per 300 g

In [16]:
# I can only get rid of duplicate columns through column selection
join_province_product[['province', 'product_types', 'currency', 'product_group_id', 'product_line_x', 'value', 'date', 'province_id', 'product_id']]

,province,product_types,currency,product_group_id,product_line_x,value,date,province_id,product_id
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,8.0,20
1,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,8.0,10
2,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,8.0,12
3,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,8.0,19
4,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3,8.0,5
...,...,...,...,...,...,...,...,...,...
1482259,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,11.0,13
1482260,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,11.0,15
1482261,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,11.0,9
1482262,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,11.0,18
1482263,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11,11.0,11

In [ ]:
# From the table, extract only the columns that refer to other tables, e.g.. product_id and the columns value, date. 
join_province_product[['product_id', 'currency', 'product_group_id', 'value', 'date', 'province_id']]

         product_id currency  product_group_id  value     date  province_id
0                20      PLN                 2  21.37   2013-3          8.0
1                10      PLN                 2  21.37   2013-3          8.0
2                12      PLN                 2  21.37   2013-3          8.0
3                19      PLN                 2  21.37   2013-3          8.0
4                 5      PLN                 2  21.37   2013-3          8.0
...             ...      ...               ...    ...      ...          ...
1482259          13      PLN                 2  11.87  2000-11         11.0
1482260          15      PLN                 2  11.87  2000-11         11.0
1482261           9      PLN                 2  11.87  2000-11         11.0
1482262          18      PLN                 2  11.87  2000-11         11.0
1482263          11      PLN                 2  11.87  2000-11         11.0

[1482264 rows x 6 columns]